/* closemenu.c generated by valac 0.25.3, the Vala compiler
 * generated from closemenu.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define TRANSFERT_WIDGETS_TYPE_CLOSE_MENU (transfert_widgets_close_menu_get_type ())
#define TRANSFERT_WIDGETS_CLOSE_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TRANSFERT_WIDGETS_TYPE_CLOSE_MENU, TransfertWidgetsCloseMenu))
#define TRANSFERT_WIDGETS_CLOSE_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TRANSFERT_WIDGETS_TYPE_CLOSE_MENU, TransfertWidgetsCloseMenuClass))
#define TRANSFERT_WIDGETS_IS_CLOSE_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TRANSFERT_WIDGETS_TYPE_CLOSE_MENU))
#define TRANSFERT_WIDGETS_IS_CLOSE_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TRANSFERT_WIDGETS_TYPE_CLOSE_MENU))
#define TRANSFERT_WIDGETS_CLOSE_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TRANSFERT_WIDGETS_TYPE_CLOSE_MENU, TransfertWidgetsCloseMenuClass))

typedef struct _TransfertWidgetsCloseMenu TransfertWidgetsCloseMenu;
typedef struct _TransfertWidgetsCloseMenuClass TransfertWidgetsCloseMenuClass;
typedef struct _TransfertWidgetsCloseMenuPrivate TransfertWidgetsCloseMenuPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _TransfertWidgetsCloseMenu {
	GtkMenu parent_instance;
	TransfertWidgetsCloseMenuPrivate * priv;
};

struct _TransfertWidgetsCloseMenuClass {
	GtkMenuClass parent_class;
};


static gpointer transfert_widgets_close_menu_parent_class = NULL;

GType transfert_widgets_close_menu_get_type (void) G_GNUC_CONST;
enum  {
	TRANSFERT_WIDGETS_CLOSE_MENU_DUMMY_PROPERTY
};
TransfertWidgetsCloseMenu* transfert_widgets_close_menu_new (void);
TransfertWidgetsCloseMenu* transfert_widgets_close_menu_construct (GType object_type);


TransfertWidgetsCloseMenu* transfert_widgets_close_menu_construct (GType object_type) {
	TransfertWidgetsCloseMenu * self = NULL;
	GtkMenuItem* file = NULL;
	GtkMenuItem* _tmp0_ = NULL;
	GtkMenuItem* quit = NULL;
	GtkMenuItem* _tmp1_ = NULL;
	GtkSeparatorMenuItem* _tmp2_ = NULL;
	GtkSeparatorMenuItem* _tmp3_ = NULL;
	self = (TransfertWidgetsCloseMenu*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("File");
	g_object_ref_sink (_tmp0_);
	file = _tmp0_;
	_tmp1_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Quit");
	g_object_ref_sink (_tmp1_);
	quit = _tmp1_;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) file);
	_tmp2_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
	g_object_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp3_);
	_g_object_unref0 (_tmp3_);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) quit);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (quit);
	_g_object_unref0 (file);
	return self;
}


TransfertWidgetsCloseMenu* transfert_widgets_close_menu_new (void) {
	return transfert_widgets_close_menu_construct (TRANSFERT_WIDGETS_TYPE_CLOSE_MENU);
}


static void transfert_widgets_close_menu_class_init (TransfertWidgetsCloseMenuClass * klass) {
	transfert_widgets_close_menu_parent_class = g_type_class_peek_parent (klass);
}


static void transfert_widgets_close_menu_instance_init (TransfertWidgetsCloseMenu * self) {
}


GType transfert_widgets_close_menu_get_type (void) {
	static volatile gsize transfert_widgets_close_menu_type_id__volatile = 0;
	if (g_once_init_enter (&transfert_widgets_close_menu_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TransfertWidgetsCloseMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) transfert_widgets_close_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TransfertWidgetsCloseMenu), 0, (GInstanceInitFunc) transfert_widgets_close_menu_instance_init, NULL };
		GType transfert_widgets_close_menu_type_id;
		transfert_widgets_close_menu_type_id = g_type_register_static (gtk_menu_get_type (), "TransfertWidgetsCloseMenu", &g_define_type_info, 0);
		g_once_init_leave (&transfert_widgets_close_menu_type_id__volatile, transfert_widgets_close_menu_type_id);
	}
	return transfert_widgets_close_menu_type_id__volatile;
}



